### ISSUE TITLE
Compilation error: exit status 1

### ISSUE THREAD

**Issue by AlbSabb** [tehniq3/GY21#1]
Hi everyone, I tried to upload the "[GY21_OLED_1.ino](https://github.com/tehniq3/GY21/blob/main/GY21_OLED_1.ino)" code into a "[WEMOS D1 Mini ESP32](https://www.az-delivery.de/it/products/esp32-d1-mini)" board (obviously with a [GY21](https://www.amazon.it/dp/B07PFHM9HN/ref=sspa_dk_detail_1?pd_rd_i=B07VF8Q7G5&pd_rd_w=iHcbk&content-id=amzn1.sym.7ef04998-a968-4397-9cab-635d55e2c83b&pf_rd_p=7ef04998-a968-4397-9cab-635d55e2c83b&pf_rd_r=TSFS7STA23AS1H3NJXDT&pd_rd_wg=KEGk6&pd_rd_r=9b17d863-f2ee-4102-b84b-5d65a3d66b58&s=industrial&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1) sensor). The IDE gives me back this error: "Compilation error: exit status 1". Can anyone explain me what is the problem and possibly how to solve it?

**Comment by tehniq3** [comment]
the sketch was test with Arduino IDE 1.8.19 and with this libraries installed:
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Fonts/FreeMonoBold18pt7b.h>
#include "Adafruit_HTU21DF.h"  // https://github.com/adafruit/Adafruit_HTU21DF_Library

by the way, error message when you compile is more longer, you put here just last line.. please use arrow to reach entire text message.. you will find all info to be ok

**Comment by AlbSabb** [comment]
Hi, I've tried to upload the code even with the old IDE (1.8.19) and gives me the same error. I've checked to have all libraries. Here all the lines of error:

c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o:(.literal._Z5setupv+0x20): undefined reference to `Adafruit_HTU21DF::begin(TwoWire*)'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o:(.literal._Z4loopv+0x14): undefined reference to `Adafruit_HTU21DF::readTemperature()'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o:(.literal._Z4loopv+0x24): undefined reference to `Adafruit_HTU21DF::readHumidity()'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_hum+0x8): undefined reference to `Adafruit_HTU21DF::Adafruit_HTU21DF()'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o: in function `setup()':
C:\Users\alber\OneDrive\Documenti\Arduino\sketch_mar28a/sketch_mar28a.ino:91: undefined reference to `Adafruit_HTU21DF::begin(TwoWire*)'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o: in function `loop()':
C:\Users\alber\OneDrive\Documenti\Arduino\sketch_mar28a/sketch_mar28a.ino:109: undefined reference to `Adafruit_HTU21DF::readTemperature()'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\alber\OneDrive\Documenti\Arduino\sketch_mar28a/sketch_mar28a.ino:110: undefined reference to `Adafruit_HTU21DF::readHumidity()'
c:/users/alber/onedrive/documenti/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\sketch_mar28a.ino.cpp.o: in function `_GLOBAL__sub_I_hum':
C:\Users\alber\OneDrive\Documenti\Arduino\sketch_mar28a/sketch_mar28a.ino:119: undefined reference to `Adafruit_HTU21DF::Adafruit_HTU21DF()'
collect2.exe: error: ld returned 1 exit status
exit status 1
Errore durante la compilazione per la scheda WEMOS D1 MINI ESP32. [Italian, original]
Compilation error for the WEMOS D1 MINI ESP32 board. [English, translated]

Thank you

Alberto

**Comment by tehniq3** [comment]
all error are related to missing  Adafruit_HTU21DF library...

**Comment by AlbSabb** [comment]
Hi @tehniq3, 
I've downloaded the library on the IDE and now it works, I appreciate that you dedicated me some of your time. Thanks again and best regards.

Alberto 

[P.S. Sorry if I made some mistakes but english isn't my first language]
